setup jsx-a11y plugin
strvcom/eslint-config-javascript pull request #20
Opened 2017-08-01 13:49 UTC by petrhanak

2017-08-02 07:03 UTC, robertrossmann commented
Thanks @petrhanak for the PR! When we discussed this addition with @dannytce we came to a conclusion that we cannot use their recommended ruleset because they set all the rules to `error`. I would like to keep that level to rules which detect broken, completely anti-pattern or otherwise extremely bad code. The rules in this plugin represent recommended best practices, therefore the rules should all be set to `warn`.

Could you please add the rules individually with their levels reduced down to `warn`? Thanks!

2017-08-16 13:55 UTC, petrhanak commented
fixed `error` => `warn` and also added comments of what rules mean

2017-08-16 14:43 UTC, robertrossmann approved these changes
Very nice! Melikes. ❤️

2017-08-16 14:44 UTC, robertrossmann commented
Waiting for additional review from @dannytce before merging.

2017-08-16 14:45 UTC, robertrossmann commented
Idea: Would it make sense to split the rules into yet another configuration file instead of adding it to the _optional.js_ ? Something like _accessibility.js_ in the _react_ family.

What do you think @petrhanak @dannytce?

2017-08-21 15:55 UTC, dannytce requested changes

2017-08-21 15:55 UTC, dannytce commented on environments/react/accessibility.js
> +    'jsx-a11y/no-onchange': 'warn',
Let's have this one as an error, because it breaks Safari

2017-08-21 15:55 UTC, dannytce commented on environments/react/accessibility.js
> +    'jsx-a11y/no-redundant-roles': 'warn',
Let's have this one as an error. It's a good practise to enforce developers to do that.

2017-08-21 17:44 UTC, robertrossmann commented on environments/react/accessibility.js
> +    'jsx-a11y/no-redundant-roles': 'warn',
If it's not absolutely terrible practice I would prefer keeping this at warn level. Best practices should not cause a failure in your test/deployment pipeline.

2017-08-25 10:19 UTC, robertrossmann commented
@dannytce Are you okay with the changes made and with my comment on your review?

@petrhanak Some last things that need be done on this before we can (finally!) merge:

- Please update the main README.md's _Available rulesets_ section
- Please update the _environments/react/README.md_ with a more detailed information about the new ruleset
- Once done, please squash all the commits into a single commit and rebase on current master, there are some conflicts

Thank you for your efforts on this!

2017-08-29 10:09 UTC, merged

2017-08-29 10:10 UTC, robertrossmann commented
Thanks, merged! I will release this together with #22 (once that's merged, too).

🍻 🎉 👍